### ISSUE TITLE
Calculation of Insertion Frequency

### ISSUE THREAD

**Issue by BisonKok** [enovoa/EpiNano#2]
Hi. Can I check with you how the insertion frequency is calculated? Thank you.

**Comment by Huanle** [comment]
Hi @BisonKok ,
Insertion frequency == number of insertion events at a given position divided by number of reads mapped to that position.

**Comment by BisonKok** [comment]
Hi Huanle,  Thanks for reply. Specifically, given the insertion event happening between reference position 301 and reference position 304, is the insertion event considered on position 301 or 304? Thank you.

**Comment by BisonKok** [comment]
Hi Huanle, Thanks for reply. Specifically, given the insertion event happening (let say 3 base insertion) between reference position 301 and reference position 302, is the insertion event considered on position 301 or 302? Does it considered as 1 or 3 events? Thank you.

**Comment by Huanle** [comment]
@BisonKok , in this specific case, the event is considered on position 301 and consider as 1 event.
This is to avoid overestimating insertion frequency, given that many reads would be mapped with insertions.

Since the downstream analysis is on k-mer(5mer) basis, the insertion events and its potential influence on determining base modification will be considered in scenarios, i.e., all kemrs containing that site and all relative positions (-2,-1,0,1,2) that site will be at in all kmers.  

That said, when it comes to single reads data, the insertion events would be evenly split between the two sites (as you can see from https://github.com/enovoa/EpiNano/blob/master/scripts/main/slide_per_read_var.py#L212).
