### ISSUE TITLE
General Questions Regarding Using EpiNano

### ISSUE THREAD

**Issue by vahidAK** [enovoa/EpiNano#34]
Hi @Huanle ,
Thanks for updating EpiNano and making it more user-friendly. I am a bit confused about how to implement EpiNano.
From my understanding, we extract per.site.var.slide features from fastq files and then we can use this file with your trained model to predict modifications? so we do not need fast5s at all?
But in the previous version, you had feature extraction from Fast5 files, which extracts features from the event table in fast5s! what was that for? because in your new instructions I do not see any command that needs Fast5s as the input file!

Thanks,
Vahid.

**Comment by Huanle** [comment]
@vahidAK sorry for getting back to you later.
The trained models were derived without taking into account the current intensity values extracted from fast5 files. This is because we found that current intensity as an extra parameter does not improve prediction accuracy. 
So yes, you can proceed without extracting this information from fast5 files. 
However, this command line and the scripts for processing fast5 files are still available in case the users are interested in exploring it themselves. 
Hope this helps.

**Comment by enovoa** [comment]
Just to clarify, you can use release 1.0 to extract current intensities. Alternatively, you can use release 1.1 for faster prediction of modified sites.

**Comment by vahidAK** [comment]
Thanks a lot, @Huanle  and @enovoa ,
I had another question, which model in the models' folder do you recommend to use?
