### ISSUE TITLE
Which model and Which column of each model has the modification status?

### ISSUE THREAD

**Issue by vahidAK** [enovoa/EpiNano#37]
Hi @Huanle and @enovoa ,

Which result (per-site or per-read) and which model in the models' folder do you recommend to use? Also, I really do not know which column in your models has the modification status. In the code example for mis3,del3,q3 you selected column 28, does this column is the same for all models in the model folder?
Can you also please explain some about the prediction output. I used the model in the example code and the result looks like this:
#Kmer,Window,Ref,Coverage,q1,q2,q3,q4,q5,mis1,mis2,mis3,mis4,mis5,ins1,ins2,ins3,ins4,ins5,del1,del2,del3,del4,del5,prediction,dist,ProbM,ProbU                             CCTGG,137039625:137039626:137039627:137039628:137039629,chr9,166.0:166.0:166.0:166.0:166.0,23.741999999999997,27.06,20.511999999999997,28.066999999999997,24.686999999999998,0.0,0.0,0.0,0.012,0.006,0.0,0.0,0.0,0.0,0.0,0.018000000000000002,0.0,0.0,0.006,0.0,unm,21.354076018509286,3.00000089999998e-14,0.9999999999999699                          TAAGA,124403220:124403221:124403222:124403223:124403224,chr10,1.0:1.0:1.0:1.0:1.0,16.0,8.0,5.0,3.0,5.0,0.0,0.0,0.0,1.0,0.0,0.5,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,mod,-0.8762640257834018,0.7606523413528626,0.2393476586471375   
So, there is also prediction for k-mers that do not have Adenin, and also for the k-mers more than one A? if a k-mer with more than one A predicted as modified, does that mean all the As in the k-mer are modified?
                                                                                                                     
Many thanks,
Vahid.

**Comment by vahidAK** [comment]
Hi @Huanle and @enovoa 
Can you please update me on the above issue?
Many thanks and Happy New Year,
Vahid.

**Comment by enovoa** [comment]
Hi @vahidAK, happy new year and apologies for slow reply. As you can imagine, we have been both on holiday break :) 
About your different questions: 

1. With regards to the output: the last two columns depict the probability of being modified (ProbM) or unmodified (ProbU) are the two last columns, which is the output of the SVM. In your specific example, probU is almost 1, i.e. it is predicted as unmodified.

2. With regards to the predictions, epinano can predict on any given kmer in principle, because it just uses mis3,del3 and q3. But the SVM predictions for kmers that are not adenine in the middle are not necessarily correct if the site contains something different than m6A. however, the extracted features may still be of interest. we kept all possible kmers because, in this way, you will know that the middle position at that kmer is containing an "increased error", which could be caused by other modifications (not just m6A). 

3. With regards to predictions in kmers with more than one A, they will also be present, for the reasons explained above. However, what we recommend doing is to subset the kmers to keep only those that match the RRACH motif. The SVM is trained on this specific subset of kmers. 

Best, Eva

**Comment by vahidAK** [comment]
Thanks a lot @enovoa  and happy new year, 
Regarding the mapping genomic coordinates to their transcript, I think it is good to keep the strand information from sam2tsv step in your results.

Thanks,
Vahid.

**Comment by enovoa** [comment]
Fully agree. We did this in an earlier version but then removed it. We will try to include it back again in the next release. Thanks for sharing your suggestion!
________________________________
