### ISSUE TITLE
CSV files for predicting and training

### ISSUE THREAD

**Issue by laguda-1996** [enovoa/EpiNano#47]
Hello, I see that fast5 file is not used in the feature extraction process. Have you used the current information of nanopore in this way？

**Comment by enovoa** [comment]
Hi @laguda-1996, the fast5 file is still used, however the version 1.1 of EpiNano does not include it as output feature, you can take a look at version 1.0 which did include current information as output (please note that it worked only with albacore base-called data). The reason for this change was that the trained models were not using current intensity as a feature to predict RNA modifications. Given the interest in including them, we are planning to release a new version that will include them back again, but will be compatible with Guppy3 basecalled data. Let us know if this clarifies your question, thanks!

**Comment by laguda-1996** [comment]
Thanks for your reply, and  I have another question.
![QQ截图20200505110836](https://user-images.githubusercontent.com/41985758/81032109-1a579080-8ec1-11ea-9c5a-2941f01c51e3.png)
There are several files in step 3. I don't know what they are

number_of_chopped_leading_bases 
number_of_chopped_end_bases 
per_rd_var.del.adjust.csv.summed.oneKmer_oneLine
 per_site.varsliding.win.csv

What are these files and how to obtain them

Looking forward to your reply, Thank you so much!

**Comment by Huanle** [comment]
Hi @laguda-1996 ,
Thanks for using Epinano. 
**number_of_chopped_leading_bases** is the number of leading bases you chopped off with **nanofilt**，
while **number_of_chopped_end_bases** is the number of bases chopped off at the end of each read.
**per_rd_var.del.adjust.csv.summed.oneKmer_oneLine**  and **per_site.varsliding.win.csv** are variants at per read/transcript leve and per reference position level respectively. 
Since the trained models are at the per reference position level, so you might want to use the per_site file. 
I am still working on to make it possible find modifcaitons are per read/transcript level. 
For the current Epinano 1.1, the including current intensities function is deprecated for we were using a naive way to infer current intesities from fast5 files. We have turned to a different approach and will release a new version that better deal with current intensities. So i recomend using v1.1 and focus on per site variants (including base qualities) for your analyses. 

I hope this makes sense to you and let me know if you think i can help further.

**Comment by laguda-1996** [comment]
Thank you for your answer and looking forward to your new version publish
