### ISSUE TITLE
explanation on output

### ISSUE THREAD

**Issue by DelphIONe** [enovoa/EpiNano#51]
Hi,

Sorry but I try to use EpiNano and I am unable to understand what is the  *.tsv.per.site.var.csv or the *.tsv.per.site.var.per_site_var.5mer.csv (output of your TSV_to_Variants_Freq.py3 script)
There is one in kmer term, an the other by position but it's by read ? How to have a coverage superior to 1 ? Where are the complete result, the real "per site" result ?

Can you explain please ? I have followed your wiki but ... it's not enough.
You advise to use a control sample and a modified sample for your Epinano-Error pipeline but how ??

Thanks for your help,

**Comment by Huanle** [comment]
Hi @DelphIONe ,
The *per.site.var.csv file contains quality score, mismatch and indel frequncies correspondent to each reference position (site). The *per_site_var.5mer.csv file simply reorganize the information of the foremer file in kmer style. 
The reason we generated the *per_site_var.5mer.csv (or any other kmer size) file is because the size of nanopore can accommodate 5/6 nucleotides, which together affect the electtrical signal during sequencing. In another word, these 5 bases are not independent from each other and better to be tacklled altogether. 

Since the output contains coverage information, you could use any threshold and filter it accordingly.

The Epinnao-Error method will be released within a couple of days with Epinano1.2. There will be example data and commands to show its usage. 

Thanks for using Epinano and I hope the above explanation is helpful. Please let me know if you think i can help more. 
Best,
Huanle

**Comment by Huanle** [comment]
Hi @DelphIONe,

You should organize your feaure table in 5mers if you want to use the pre-trained model. 
slide_per_site_var.py should do the job for you.
What's the size of your input file? 
As for the *-cl*, you should choose the column number (1-based) in the slided feature table and corresponding to the features used for training. 

I do not expect there would be any RAM asscociated problem with this specific operation given that the script store and process k(user defined)-lines at any time. 
If you do not mind, can you send me your input file so that i can have a test?

**Comment by Huanle** [comment]
Hi @DelphIONe,

It is ok to use -cl 5,8,10, if using no-slided feature table for input. 
Sorry i mistook your purpose and thought you would like to use features from consecutive sites.
