### ISSUE TITLE
WT vs KO considerations

### ISSUE THREAD

**Issue by Wardale24** [enovoa/EpiNano#53]
Hello,

I am unsure how to proceed with the new version of Epinano (1.2). You mention I can use the trained SVM for m6A if it is basecalled with Guppy 3.1.5, but also strongly recommend using a demethylated control (WT vs KO/KD) and your own trained model?

In this case, say we have 3 samples, each one is a developmental stage of a wild type organism. According to your recommendation, I should sequence the three stages normally, with modified bases, each one being considered a WT sample. After this I should sequence one separate sample treated with demethylase and use it as a KO sample.

But then what? You mention to make your own model, but also to use these WT and KO samples pairwise. I am unsure what to use to train my own model that you strongly recommend.

**Comment by Huanle** [comment]
Hi @Wardale24 ,

We recommend using paired samples because we found that using the differences of those error features between samples tend to predict more accurately.

In the test data folder, i offered some examples training and predicting commands, which you can refer to.

In your case, if you want to train models using KO-WT deviance, you can have one sample without any modificaiton at all and at least one WT sample with known modifications so that you can compute WT-KO deviance and use it to train models. 


Let me know if this makes sense to you?

**Comment by Wardale24** [comment]
Hello Huanle,
 
This clarifies a lot, thank you very much. I was thinking that I would have to train the model for each specific sample but I realize now that was wrong.

Thanks for the reply,

AW
