### ISSUE TITLE
Dependencies required to run epinano toolset

### ISSUE THREAD

**Issue by a-slide** [enovoa/EpiNano#71]
Hi @Huanle and @enovoa,

I could not find a detailed list of the dependencies required to run Epinano except the 2 packages mentioned in the `INSTALL.sh` script. I followed the instructions but I keep having dependencies issue while trying to run `Epinano_Predict.py`. 
I identified at least 5 third party python packages imported in the source files but not listed in the install script 
- scikit-learn
- numpy
- biopython
- pysam
- matplotlib

However I have no idea which versions are required and so far I could not find a combination which works.

In addition there are a number of non-Python dependencies required to run the full pipeline, including R packages and extra tools such as nanopolish and minimap.

Would you be able to provide a detailed list of all the dependencies and the versions required to run the entire toolset ?

An ideal solution would be a conda package available on Anaoconda Cound, but a conda `environment.yml` file exported from a local working environment would also be a good solution (https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#sharing-an-environment).

Thanks

**Comment by Huanle** [comment]
Hi @a-slide ,

The dependencies are mentioned in https://github.com/enovoa/EpiNano#pre-requisites.
I did miss pysam (0.15.3) and matplotlib (3.3.2) though the foremer one is supposed to be removed because i did not to use it in the end, i will update the script. 

All relevant R PKGs were installed for R v3.6.0. I will add them to the pre-requisites as well.

Thanks a lot for the conda pkg management suggection, i will give it a go.

**Comment by a-slide** [comment]
Thanks @Huanle
