### ISSUE TITLE
Get the profile of modification in serval sample 

### ISSUE THREAD

**Issue by solaryx** [enovoa/EpiNano#80]
Can I use EpiNano-Error to get the result of both sample?

**Comment by Huanle** [comment]
Hi @solaryx ,

All Epinano-Error does it to predict the most likely modified sites by comparing two the potentially modified and unmodified samples. 

I think you have mixed it with the Epinano_predict algorithm, which does predict the modification status of any sample provided to make predictions.

Regarding your sample-labeling [question](https://github.com/enovoa/EpiNano/issues/78#issue-785985323): Labeling the modified and un-modified samples is required to train your own models with Epinano_Predict. This requires prior knowledge of modification sites in your samples. In the example, all As in RRACH motifs are modified in the WT sample.  
In your case, since you do not have this information, you can not do training. But you can use Epinano_predict to predict m6A modifications using the already trained models that are included in the Epinano repository.
